services:

  django:
    container_name: django
    hostname: django
    build:
      context: .
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - my_kanban2_db:/app/db
      - my_kanban2_static:/app/staticfiles
      - my_kanban2_media:/app/media
    restart: no
    command: gunicorn my_kanban2.wsgi --bind 0.0.0.0:8000
    networks: 
      - my_kanban2_network

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.26.2-alpine
    ports:
      - 80:80
    volumes:
      - my_kanban2_static:/app/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: no
    depends_on:
      - django
    networks: 
    - my_kanban2_network


networks:
  my_kanban2_network:

volumes:
  my_kanban2_static:
  my_kanban2_media:
  my_kanban2_db:
