services:

  postgresql:
    container_name: postgresql
    hostname: postgresql
    image: postgres:13-alpine
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data/
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 4
    networks: 
      - network
    
  redis:
    container_name: redis
    hostname: redis
    image: redis:7.4.0-alpine
    expose:
      - 6379
    env_file:
      - .env
    volumes:
      - invitations:/data
    restart: no
    entrypoint: ["redis-server"]
    command: ["--requirepass", "$REDIS_PASSWORD"]
    networks:
      - network
    
  django:
    container_name: django
    hostname: django
    build:
      context: .
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    restart: no
    command: ["/app/entrypoint.sh"]
    depends_on:
      postgresql:
        condition: service_healthy
    networks: 
      - network

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.26.2-alpine
    ports:
      - 80:80
    volumes:
      - static:/app/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: no
    depends_on:
      - django
    networks: 
    - network


networks:
  network:

volumes:
  static:
  media:
  db:
  invitations:
