# Generated by Django 4.2 on 2024-07-12 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import thisapp.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thisapp', '0003_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, default=None, null=True,
                 upload_to='user_uploads', validators=[thisapp.validators.validate_file_size])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='own_comments', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                           to='thisapp.card')),
            ],
        ),
    ]
