# Generated by Django 4.2 on 2024-09-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thisapp', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.IntegerField(choices=[(1, 'Backlog'), (2, 'In progress'), (3, 'Done')], default=1),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
