name: Django Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run tests
        run: docker compose -f docker-compose-test.yml up --build --abort-on-container-exit --exit-code-from django

      - name: Tear down
        run: docker compose -f docker-compose-test.yml down -v
